Changing index.html
ok-technopolis-autumn-2019/Artem_Gerasimov pull request #1
Opened 2019-10-11 16:01 UTC by art241111

Прошу прощения, что так поздно, к сожалению не мог сделать ранее.

2019-10-12 20:06 UTC, fromanywhere requested changes

2019-10-12 20:06 UTC, fromanywhere commented on app/src/index.html
> +    <link rel="stylesheet" type="text/css" href="css/style.css" >
Выглядит лишним

2019-10-12 20:06 UTC, fromanywhere commented on app/src/index.html
> +              aria-label="Completed task: HTML"
Здесь aria-label не соответствует действительности

2019-10-12 20:06 UTC, fromanywhere commented on app/src/index.html
> +              type="radio"
Не забывайте атрибут name

2019-10-12 20:06 UTC, fromanywhere commented on app/src/index.html
> +            <span class="task-item"> All </span>
Следовало бы увеличить область клика с использованием <label>

2019-10-13 09:15 UTC, art241111 commented on app/src/index.html
> +            <span class="task-item"> All </span>
Немного не понял данное замечание, что именно нужно подправить?

2019-10-13 17:02 UTC, fromanywhere commented on app/src/index.html
> +            <span class="task-item"> All </span>
Через css — это пытаться радиокнопку растянуть абсолютом поверх текста, что ли, с прозрачностью? Это конечно сработает, но лучше где-то здесь использовать label, слинкованный с радиокнопкой. Тут может быть два пути — либо все оставить как есть, только span.task-item поменять на label, радиокнопке написать id, labelу написать такой же for, и всё заведется. Либо всё оставить как есть, div.selected-item__view заменить на label, и раз радиокнопка окажется внутри, то любой клик в label, в т.ч. в рядом лежащий текст, попадет и в радиокнопку тоже

2019-10-13 17:03 UTC, fromanywhere commented on app/src/index.html
> +                value = "Completed"
Форматирование не забываем соблюдать единообразно

2019-10-13 18:35 UTC, art241111 commented on app/src/index.html
> +            <span class="task-item"> All </span>
Понял, спасибо!

2019-10-13 19:00 UTC, fromanywhere approved these changes

2019-10-14 08:52 UTC, merged