Adding style
ok-technopolis-autumn-2019/Artem_Gerasimov pull request #2
Opened 2019-10-14 19:36 UTC by art241111

К сожалению не получилось оформить checkbox. А так постарался сделать, что-то похожее на макет.

2019-10-15 09:13 UTC, fromanywhere requested changes

2019-10-15 09:13 UTC, fromanywhere commented on app/src/css/style.css
> +
Хорошо!

2019-10-15 09:13 UTC, fromanywhere commented on app/src/css/actions-bar.css
> +    width: 601px;
А вот если бы у приложения была общая обертка, то не пришлось бы писать ширину в двух разных местах, да и потом выравнивать всё было бы значительно легче

2019-10-15 09:13 UTC, fromanywhere commented on app/src/css/actions-bar.css
> +    flex-direction: column;
Группировка свойств по смысл, потрясающе, я об этом даже упоминать опасался. Это так учат где-то или свой подход?

2019-10-15 09:13 UTC, fromanywhere commented on app/src/css/actions-bar.css
> +    outline: 1px solid #bfbfbf;
лучше не использовать outline для таких целей. У него с геометрией не очень, в box-model оно нормально не ложится, всякая декоративная геометрия вроде border-radius на нем не работает, и вообще лучше оставить его для индикации фокуса, как это по умолчанию в браузере

2019-10-15 09:13 UTC, fromanywhere commented on app/src/css/actions-bar.css
> +    box-shadow: 0 0 8px -1px #99989d;
отдельная тень на футере — так себе. Стык виден. Лучше общую тень на общий контейнер

2019-10-15 09:13 UTC, fromanywhere commented on app/src/css/body.css
> +    flex-wrap: nowrap;
оно по умолчанию такое

2019-10-15 09:13 UTC, fromanywhere commented on app/src/css/footer.css
> +        display: none;
здесь умер фокус с клавиатуры

2019-10-15 09:13 UTC, fromanywhere commented on app/src/css/footer.css
> +    .selected-item__view input[type=radio]:checked + span {
опасно вешать селектор по тегу, когда вне рамок каких-то экспериментов в песочнице

2019-10-15 09:13 UTC, fromanywhere commented on app/src/css/footer.css
> +    font-family: "Times New Roman", serif;
Антикву-то за что?

2019-10-15 09:13 UTC, fromanywhere commented on app/src/css/header.css
> +    font-family: "Giger", serif;
А можно было бы просто взять roboto с макета...

2019-10-15 09:13 UTC, fromanywhere commented on app/src/css/main-controls.css
> +    outline: none;
Здесь не просто умер фокус, здесь он явно убит

2019-10-15 09:13 UTC, fromanywhere commented on app/src/css/main-controls.css
> +    background-image: url("../img/arrow.png");
картинок в коммите нет

2019-10-15 09:13 UTC, fromanywhere commented on app/src/css/main-controls.css
> +    background-size: 20px 12px;
поэтому я не могу оценить Ваш подход к графике на дисплеях с повышенной плотностью aka ретина

2019-10-15 09:13 UTC, fromanywhere commented on app/src/css/main-controls.css
> +    overflow: hidden;
вроде вот это уже лишнее

2019-10-15 09:13 UTC, fromanywhere commented on app/src/css/footer.css
> +        border: 1px solid #999;
Тут при клике пункты будут немного прыгать по горизонтали, нужно подумать

2019-10-15 09:13 UTC, fromanywhere commented on app/src/css/tasks.css
> +}
Много хорошего и много избыточных стилей. Самое слабое в этой работе — очень мелкие кликабельные области всех элементов, нужно быть снайпером, чтобы всем этим нормально пользоваться. Картину дополняет не просто потерянные фокусы, а намеренно скрытые, это вот вообще совсем нехорошо

2019-10-23 17:41 UTC, art241111 commented on app/src/css/actions-bar.css
> +    flex-direction: column;
Если честно, то не знаю)) Я очень давно занимался фронтендом и может это с тех курсов, но вообще мне просто так удобнее ориентироваться в коде.

2019-10-24 16:16 UTC, fromanywhere approved these changes

2019-10-24 16:16 UTC, fromanywhere commented on app/src/css/body.css
> +        @include shadow;
это уже что-то из третьей лабы

2019-10-24 16:24 UTC, merged

2019-10-24 16:25 UTC, art241111 commented on app/src/css/body.css
> +        @include shadow;
Да, начал немного набрасывать во время занятия, забыл удалить(